version: '3.4'

x-defaults: &defaults
  restart: unless-stopped
  networks:
    - main
  logging:
    driver: loki
    options:
      loki-url: "http://localhost:3100/api/prom/push"
  
services:
  uploader:
    <<: *defaults
    build: .
    env_file:
      - ./.env
    ports:
      - 8000:8000
    volumes:
       - data:/usr/src/uploader/uploads
    
networks:
  main:
    external: true

volumes:
  data: