version: '3.4'
  
services:
  uploader:
    image: hichuyamichu/uploader:latest
    volumes:
      - data:/uploder/data
      - ./config.yaml:/uploder/config.yaml
    restart: unless-stopped
    networks:
      - main
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/api/prom/push"
    
networks:
  main:
    external: true

volumes:
  data: