version: '3.4'
  
services:
  uploader:
    build: .
    restart: unless-stopped
    volumes:
      - data:/uploder/data
    networks:
      - dev
    ports:
      - 9000:9000

networks:
  dev:
    external: true

volumes:
  data: