version: '3.4'

services:
  goober:
    build: .
    restart: unless-stopped
    volumes:
      - data:/uploder/data
      - ./config.yaml:/uploder/config.yaml
    networks:
      - dev
    ports:
      - 9000:9000

networks:
  dev:
    external: true

volumes:
  data:
