version: '3.4'
  
services:
  uploader:
    build: .
    env_file:
      - ./.env
    volumes:
       - data:/usr/src/uploader/upload
    restart: unless-stopped
    networks:
      - main
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/api/prom/push"
    
networks:
  main:
    external: true

volumes:
  data: